version: "3.4"
services:
  slasher:
    restart: "${RESTART}"
    user: ${LOCAL_UID}:${LOCAL_UID}
    build:
      context: ./prysm
      target: slasher
      dockerfile: ${PRYSM_DOCKERFILE}
      args:
        - BUILD_TARGET=${PRYSM_SRC_BUILD_TARGET}
        - USER=${PRYSM_USER}
        - UID=${LOCAL_UID}
        - DOCKER_TAG=${PRYSM_DOCKER_TAG}
    image: prysm-slasher
    expose:
      - 8082
    volumes:
      - prysmslasher-data:/var/lib/prysm
    entrypoint:
      - slasher
      - --datadir
      - /var/lib/prysm
      - --beacon-rpc-provider
      - beacon:4000
      - --monitoring-host
      - 0.0.0.0
      - --verbosity
      - ${LOG_LEVEL}
      - --${NETWORK}
      - --accept-terms-of-use
    depends_on:
      - beacon
  eth2:
    image: tianon/true
    restart: "no"
    depends_on:
      - slasher
volumes:
  prysmslasher-data:
